services:
  - type: web
    name: viralclipsaver-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - api/**
    rootDir: api
    autoDeploy: true
